name: Deploy to Staging

run-name: ${{github.actor}} initiated the workflow - Deploy To Testing

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: testing node
        run: |
          echo "node version is:"
          node -v
          npm -v
          
      - name: Install Dependencies
        run: |
          cd devapp
          npm i

      - name: Build Project
        run:  |
          cd devapp
          npm run build

      - name: Unit Testing
        run:  |
          cd devapp
          npm test

      - name: Deploy to AWS Staging Server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@13.51.178.191'
          privatekey: ${{secrets.ssh_key_dev_3}}
          command: |
            export NVM_DIR=/home/ubuntu/.nvm
            source /home/ubuntu/.nvm/nvm.sh
            cd /home/ubuntu/Assignment3/
            pwd
            docker-compose up -d
            
      - name: deployment message passed
        if: success()
        run: |
           echo "deployment passed"
           
      - name: deployment message failed
        if: failure()
        run: |
           echo "deployment failed"
          

